### PR TITLE
Upgrade to MudBlazor 7

### PR DESCRIPTION
**Pull request by sfmskywalker**
This PR upgrades to MudBlazor from 6.x to 7.x

The latest version of MudBlzor is 7.9.0, but because MudBlazorExtensions still targets 7.3.0, we can't go all the way to 7.9.0 for now, due to an API change introduced after 7.3.0 that causes a Missing Method exception at runtime.

I created a PR for that here: https://github.com/CodeBeamOrg/CodeBeam.MudBlazor.Extensions/pull/472

### CODE REVIEW

**Comment by entech-trice** [comment]
Hey @sfmskywalker !

Thanks for the update! Anything else needed for this or is it good to go? Just need to merge now?

Thanks,
Travis

**Comment by sfmskywalker** [comment]
Hi @entech-trice , this is already part of the main branch, so it should be all good! The purpose of this PR was to update the blueberry branch, which is an intermediary step between 3.2 and 3.3 for certain users not ready to move to the unstable 3.3 previews, while being "too big" of a change to warrant another patch on 3.2. That said, if you are you using the blueberry builds and you want the update to Blazor 7, we can certainly merge this now.

**Comment by entech-trice** [comment]
Awesome! Thanks for the clarification @sfmskywalker.

**Comment by sfmskywalker** [comment]
Closing this because we don't need it for the temporary blueberry branch and because it's already done in the main branch.

**Pull request closed without merging**
